# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8718d72376053217ed772ad4220dc547b3cc7a76014d862eafe41a589518be40d57cc3c4fda69fd33e9f8f48c3b7ddab701a801e6c51dac884d4935726ea849a

test:
  secret_key_base: 7d14fb6b0efe3cade8413721c33bd9f7bf90d4f4a7ec4653207cc231c5463b12545c601adc18576de8951c117a8e81e3e7bde9fa455ac1f1eeec8840c1a2ae3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
